// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irudsiapgsuqbfaymjbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlydWRzaWFwZ3N1cWJmYXltamJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDk1NjYsImV4cCI6MjA3MzUyNTU2Nn0.cj09RDQSys3wcfYDNNBlRQq9hSu25ndhd4uXtrrWsnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});